ALTER TABLE event ADD CONSTRAINT FK_EVENT_MODLE FOREIGN KEY (modle) REFERENCES modle ON DELETE CASCADE ;
ALTER TABLE event ADD CONSTRAINT FK_EVENT_ROOM FOREIGN KEY (room)REFERENCES room ON DELETE CASCADE;
ALTER TABLE attends ADD CONSTRAINT FK_ATTENDS_EVENT FOREIGN KEY (event)REFERENCES event (id) ON DELETE CASCADE;
ALTER TABLE attends ADD CONSTRAINT FK_ATTENDS_STUDENT FOREIGN KEY (student)REFERENCES student (id) ON DELETE CASCADE;
ALTER TABLE teaches ADD CONSTRAINT FK_TEACHES_STAFF FOREIGN KEY (staff)REFERENCES staff (id) ;
ALTER TABLE teaches ADD CONSTRAINT FK_TEACHES_EVENT FOREIGN KEY (event)REFERENCES event (id) ON DELETE CASCADE;
ALTER TABLE occurs ADD CONSTRAINT FK_OCCURS_EVENT FOREIGN KEY (event)REFERENCES event (id) ON DELETE CASCADE;
ALTER TABLE occurs ADD CONSTRAINT FK_OCCURS_WEEK FOREIGN KEY (week)REFERENCES week (id) ON DELETE CASCADE;