ALTER TABLE room ADD CONSTRAINT PK_ROOM PRIMARY KEY(id);
ALTER TABLE modle ADD CONSTRAINT PK_MODLE PRIMARY KEY(id);
ALTER TABLE event ADD CONSTRAINT PK_EVENT PRIMARY KEY(id);
ALTER TABLE occurs ADD CONSTRAINT PK_OCCURS PRIMARY KEY(event,week);
ALTER TABLE week ADD CONSTRAINT PK_WEEK PRIMARY KEY(id);
ALTER TABLE teaches ADD CONSTRAINT PK_TEACHES PRIMARY KEY(staff,event);
ALTER TABLE student ADD CONSTRAINT PK_STUDENT PRIMARY KEY(id);
ALTER TABLE attends ADD CONSTRAINT PK_ATTENDS PRIMARY KEY(student,event);