ALTER TABLE Unidades Drop constraint FK_Unidades_SURTIM;
ALTER TABLE Abastecimientos drop CONSTRAINT FK_ABASTECIMIENTOS_PRODUCTOS;
ALTER TABLE Juegos drop CONSTRAINT FK_JUEGOS_PRODUCTOS;
ALTER TABLE Ofrecimientos drop CONSTRAINT FK_OFRECIMIENTOS_PRODUCTO;
ALTER TABLE Compras drop CONSTRAINT FK_COMPRAS_PROVEEDORES ;


ALTER TABLE Unidades ADD CONSTRAINT FK_Unidades_SURTIM 
    FOREIGN KEY (surtimiento) REFERENCES Surtimientos on delete cascade;
ALTER TABLE Juegos ADD CONSTRAINT FK_JUEGOS_PRODUCTOS 
    FOREIGN KEY (producto) REFERENCES Productos on delete cascade;
ALTER TABLE Abastecimientos ADD CONSTRAINT FK_ABASTECIMIENTOS_PRODUCTOS 
    FOREIGN KEY (producto) REFERENCES Productos on delete set null;
ALTER TABLE Compras ADD CONSTRAINT FK_COMPRAS_PROVEEDORES 
    FOREIGN KEY (proveedor) REFERENCES Proveedores on delete set null;
ALTER TABLE Ofrecimientos ADD CONSTRAINT FK_OFRECIMIENTOS_PRODUCTO 
    FOREIGN KEY (producto) REFERENCES Productos on delete cascade;

