--crudok
execute PC_Producto.Ad_Producto(140,'msi','ventialadores','N/A','Tecnologia','5','40x20x13');
execute PC_Categoria.AD_Categoria(8,'qqqqq','N/A');
execute PC_Categoria.EL_Categoria(8);
execute PC_Proveedor.Ad_Proveedor('123451234-1','qqqq','3005973325','kra234-129','qqq@mail.com','NIT','32',120);
execute PC_Proveedor.Mo_Proveedor('123451234-1','qqqq','3005973326','kra234-129','qqq@mail.com');
execute PC_Producto.Ad_Producto(140,'msi','ventiladores','N/A','Tecnologia','5','40x20x13');
execute PC_Producto.MO_Producto(35,144,'msi','N/A','Tecnologia','5');
execute PC_Producto.AD_Juego('N/A',xmltype('<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Ficha_tecnica[<!ELEMENT Ficha_tecnica (Juego)><!ELEMENT Juego (Genero, Plataformas,Fecha_Lanzamiento, Formato, Clasificacion_ESRB, Calificacion_Metacritic, Idiomas, Modos+ )><!ATTLIST Juego espacio_requerido CDATA #REQUIRED><!ELEMENT Genero (#PCDATA)> <!ATTLIST Genero Nombre CDATA #REQUIRED>	<!ELEMENT Plataformas (Plataforma+)><!ELEMENT Plataforma (#PCDATA)><!ATTLIST Plataforma Nombre  CDATA #REQUIRED><!ELEMENT Fecha_Lanzamiento (#PCDATA)><!ATTLIST Fecha_Lanzamiento Fecha CDATA #REQUIRED><!ELEMENT Formato (#PCDATA)><!ATTLIST Formato Nombre CDATA #REQUIRED><!ELEMENT Clasificacion_ESRB (#PCDATA)><!ATTLIST Clasificacion_ESRB Clasificacion CDATA #REQUIRED><!ELEMENT Calificacion_Metacritic (#PCDATA)><!ATTLIST Calificacion_Metacritic Calificacion CDATA #REQUIRED><!ELEMENT Idiomas (Idioma+)><!ELEMENT Idioma (#PCDATA)><!ATTLIST Idioma Idioma_Juego CDATA #REQUIRED><!ELEMENT Modos (Modo+)><!ELEMENT Modo (#PCDATA)><!ATTLIST Modo Modo_Juego CDATA #REQUIRED>]><Ficha_tecnica><Juego espacio_requerido= "40.5 GB" ><Genero Nombre="Accion"> </Genero><Plataformas><Plataforma Nombre="Xbox one"> </Plataforma></Plataformas><Fecha_Lanzamiento Fecha="20/05/2018"> </Fecha_Lanzamiento><Formato Nombre="Fisico"> </Formato><Clasificacion_ESRB Clasificacion="M"> </Clasificacion_ESRB><Calificacion_Metacritic Calificacion = "77"> </Calificacion_Metacritic><Idiomas><Idioma  Idioma_Juego="Español"> </Idioma><Idioma Idioma_Juego="Ingles"> </Idioma></Idiomas><Modos><Modo Modo_Juego="Multijugador"> </Modo><Modo Modo_Juego="Online"> </Modo><Modo Modo_Juego="Un jugador"> </Modo><Modo Modo_Juego="Offline"> </Modo>	</Modos></Juego></Ficha_tecnica>'),140,'bethesda','TSO4','N/A','Juego','7','10x10x13');
execute PC_Producto.MO_Juego(37,'conexion permanente a internet',xmltype('<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Ficha_tecnica[<!ELEMENT Ficha_tecnica (Juego)><!ELEMENT Juego (Genero, Plataformas,Fecha_Lanzamiento, Formato, Clasificacion_ESRB, Calificacion_Metacritic, Idiomas, Modos+ )><!ATTLIST Juego espacio_requerido CDATA #REQUIRED><!ELEMENT Genero (#PCDATA)> <!ATTLIST Genero Nombre CDATA #REQUIRED>	<!ELEMENT Plataformas (Plataforma+)><!ELEMENT Plataforma (#PCDATA)><!ATTLIST Plataforma Nombre  CDATA #REQUIRED><!ELEMENT Fecha_Lanzamiento (#PCDATA)><!ATTLIST Fecha_Lanzamiento Fecha CDATA #REQUIRED><!ELEMENT Formato (#PCDATA)><!ATTLIST Formato Nombre CDATA #REQUIRED><!ELEMENT Clasificacion_ESRB (#PCDATA)><!ATTLIST Clasificacion_ESRB Clasificacion CDATA #REQUIRED><!ELEMENT Calificacion_Metacritic (#PCDATA)><!ATTLIST Calificacion_Metacritic Calificacion CDATA #REQUIRED><!ELEMENT Idiomas (Idioma+)><!ELEMENT Idioma (#PCDATA)><!ATTLIST Idioma Idioma_Juego CDATA #REQUIRED><!ELEMENT Modos (Modo+)><!ELEMENT Modo (#PCDATA)><!ATTLIST Modo Modo_Juego CDATA #REQUIRED>]><Ficha_tecnica><Juego espacio_requerido= "40.5 GB" ><Genero Nombre="Accion"> </Genero><Plataformas><Plataforma Nombre="Xbox one"> </Plataforma></Plataformas><Fecha_Lanzamiento Fecha="20/05/2018"> </Fecha_Lanzamiento><Formato Nombre="Fisico"> </Formato><Clasificacion_ESRB Clasificacion="M"> </Clasificacion_ESRB><Calificacion_Metacritic Calificacion = "77"> </Calificacion_Metacritic><Idiomas><Idioma  Idioma_Juego="Español"> </Idioma><Idioma Idioma_Juego="Ingles"> </Idioma></Idiomas><Modos><Modo Modo_Juego="Multijugador"> </Modo><Modo Modo_Juego="Online"> </Modo><Modo Modo_Juego="Un jugador"> </Modo><Modo Modo_Juego="Offline"> </Modo>	</Modos></Juego></Ficha_tecnica>'));
execute PC_Producto.DEL_Juego(37);
execute PC_Proveedor.Mo_Ofrecimiento('123451234-1','32',118);
execute PC_Compra.Ad_Compra('123451234-1',32,118,'negro',1);
execute PC_Bodega.AD_Bodega(7,'kra234-130',400);
execute PC_Surtimiento.AD_Surtimiento(40,4);
select * from surtimientos;
execute PC_Unidad.Ad_unidad('1234123','blanco',32,40);
execute PC_Surtimiento.MO_Surtimiento(40,'A');
execute PC_Surtimiento.EL_Surtimiento(40);
execute PC_Bodega.EL_Bodega(5);
execute PC_Proveedor.El_Ofrecimiento('123451234-1',32);
execute PC_Proveedor.El_Proveedor('123451234-1');
select PC_Unidad.Co_unidades from dual;
select PC_Unidad.Co_Unidades_Producto(29) from dual;
select PC_Proveedor.Co_Mejores_Ofrecimientos from dual;
select PC_Proveedor.Co_Proveedores from dual;
select PC_Proveedor.Co_Ofrecimientos FROM DUAL;
select PC_Proveedor.Co_Ofrecimientos_Proveedor('665308893-4') from dual;
select PC_Compra.Co_compras from dual;
select PC_Compra.Co_detalle_compras from dual;
select PC_Compra.Co_compras_Proveedor('665308893-4') from dual;
select PC_Producto. Co_Juegos_Plataforma('PC') from dual;
select PC_Producto.CO_Juegos from dual;
select PC_Producto.Co_Productos from dual;
select PC_Producto.CO_Productos_Marca('Sony') from dual;
select PC_Producto.CO_Productos_Categoria('2') from dual;
select PC_Producto.Co_Productos_Tipo('Tecnologia') from dual;
select PC_Producto.Co_Info_Producto from dual;
select PC_Categoria.CO_Categorias from dual;
select PC_Surtimiento.Co_Surtimientos  from dual;
select PC_Surtimiento.Co_Surtimientos_Estado('E',to_date('06/06/2018','mm/dd/yyyy')) from dual;
select PC_Bodega.Co_Bodegas from dual;
select PC_Bodega.Co_Capacidad_restante from dual;