--FKs
ALTER TABLE Productos ADD CONSTRAINT FK_PRODUCTOS_CATEGORIA
    FOREIGN KEY(categoria) REFERENCES Categorias;
ALTER TABLE Unidades ADD CONSTRAINT FK_Unidades_SURTIM 
    FOREIGN KEY (surtimiento) REFERENCES Surtimientos on delete cascade;
ALTER TABLE Unidades ADD CONSTRAINT FK_Unidades_PRODUCTO 
    FOREIGN KEY (producto) REFERENCES Productos ;
ALTER TABLE Juegos ADD CONSTRAINT FK_JUEGOS_PRODUCTOS 
    FOREIGN KEY (producto) REFERENCES Productos on delete cascade;
ALTER TABLE Abastecimientos ADD CONSTRAINT FK_ABASTECIMIENTOS_PRODUCTOS 
    FOREIGN KEY (producto) REFERENCES Productos on delete set null;
ALTER TABLE Abastecimientos ADD CONSTRAINT FK_ABASTECIMIENTOS_COMPRAS 
    FOREIGN KEY (compra) REFERENCES Compras;
ALTER TABLE Compras ADD CONSTRAINT FK_COMPRAS_PROVEEDORES 
    FOREIGN KEY (proveedor) REFERENCES Proveedores on delete set null;
ALTER TABLE Ofrecimientos ADD CONSTRAINT FK_OFRECIMIENTOS_PRODUCTO 
    FOREIGN KEY (producto) REFERENCES Productos on delete cascade;
ALTER TABLE Ofrecimientos ADD CONSTRAINT FK_OFRECIMIENTOS_PROVEEDORES 
    FOREIGN KEY (proveedor) REFERENCES Proveedores ;
ALTER TABLE Surtimientos ADD CONSTRAINT FK_SURTIMIENTOS_BODEGAS
    FOREIGN KEY (bodega)REFERENCES Bodegas;

    
ALTER TABLE Surtimientos ADD CONSTRAINT FK_SURTIMIENTOS_COMPRAS
    FOREIGN KEY (compra)REFERENCES compras ;