--PKs
ALTER TABLE Surtimientos ADD CONSTRAINT PK_SURTIMIENTOS
    PRIMARY KEY(numero);
ALTER TABLE Abastecimientos ADD CONSTRAINT PK_ABASTECIMIENTOS 
    PRIMARY KEY(linea_compra);
ALTER TABLE Bodegas ADD CONSTRAINT PK_BODEGAS
    PRIMARY KEY(numero);
ALTER TABLE Categorias ADD CONSTRAINT PK_CATEGORIAS 
    PRIMARY KEY(numero);
ALTER TABLE Compras ADD CONSTRAINT PK_COMPRAS 
    PRIMARY KEY(numero);
ALTER TABLE Ofrecimientos ADD CONSTRAINT PK_OFRECIMIENTOS 
    PRIMARY KEY(producto,proveedor);
ALTER TABLE Unidades ADD CONSTRAINT PK_UNIDADES
    PRIMARY KEY(numero_de_serie);
ALTER TABLE Juegos ADD CONSTRAINT PK_JUEGOS 
    PRIMARY KEY(producto);
ALTER TABLE Productos ADD CONSTRAINT PK_PRODUCTOS 
    PRIMARY KEY(id_producto);
ALTER TABLE Proveedores ADD CONSTRAINT PK_PROVEEDORES 
    PRIMARY KEY(identificacion);