--Uks----
ALTER TABLE Productos ADD CONSTRAINT UK_PRODUCTOS
    UNIQUE(nombre);
ALTER TABLE Categorias ADD CONSTRAINT UK_CATEGORIAS
    UNIQUE(nombre);
ALTER TABLE Bodegas ADD CONSTRAINT UK_DIRECCION_BODEGA
    UNIQUE(direccion);
ALTER TABLE Proveedores ADD CONSTRAINT UK_CORREO
    UNIQUE(correo);
ALTER TABLE Proveedores ADD CONSTRAINT UK_DIRECCION_PROVEEDOR
    UNIQUE(direccion);